services:
  web:
    container_name: clube-front
    build: 
      context: ./clube-front/
    ports:
      - "80:80"
    volumes:
      - ./clube-front:/app
      - /app/node_modules
    # command: npm run dev
    env_file:
      - .env
    depends_on:
      - back
    networks:
      - app-network

  back:
    container_name: back
    build:
      context: ./back/
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    env_file:
      - .env
    command: poetry run flask run --host=0.0.0.0 --port=5000 --debug
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    container_name: club-database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tasks_manager
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    container_name: club-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin 
    depends_on:
      - mongo
    networks:
      - app-network

  redis:
    container_name: club-redis
    image: redis:7.2-alpine
    restart: always
    command: "redis-server --requirepass ${DOCKER_REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
